### PR TITLE
WIP: fix: use ascii names and custom map

### LINKED ISSUE #190: Remove non-ascii symbols from API
Reminder to follow up on the Slack discussion. I think everyone agrees it only creates problems and adds no value to have them.
Uppercase remains, and we can do normalization stuff to support better English names.

### PR DESCRIPTION
**Pull request by ayuhito**
Closes #190 and #163.

I removed the city element from the Regex as I'm not sure it's valid to denote places like Kansas City or Mexico City as other names. But I guess the same logic could be applied to New York as that can also be considered a state just like Kansas. Thoughts?

I think we should reopen #163 if we think maintaining a manual map is actually taking too much developer time in the long run, which I highly highly doubt. Otherwise, this should be suitable. 

This also fixes a bug with location filtering. While the probe on the demo/api results shows 'Kansas City', you can't use 'Kansas City' as the filter but only 'Kansas'. This makes both what's shown to the user and what should be inputted to be the same and unambiguous.

### CODE REVIEW

File: src/lib/geoip/utils.ts [hunk 1]
```diff
@@ -1,5 +1,20 @@
 import anyAscii from 'any-ascii';
 
-export const normalizeCityName = (name: string): string => anyAscii(name).toLowerCase().replace(/(?:\s+|^)(?:the|city)(?:\s+|$)/gi, '');
+/* eslint-disable @typescript-eslint/naming-convention */
+const altNames: Record<string, string> = {
```
Comment (patrykcieszkowski) [inline src/lib/geoip/utils.ts:4]: we should move aliases to a seperate file. Just like we did for ISP names.

https://github.com/jsdelivr/globalping/blob/master/src/lib/location/networks.ts

File: src/lib/geoip/altnames.ts [hunk 2]
```diff
@@ -0,0 +1,6 @@
+/* eslint-disable @typescript-eslint/naming-convention, quote-props */
+export const altNames: Record<string, string> = {
```
Comment (patrykcieszkowski) [inline src/lib/geoip/altnames.ts:2]: The variable should be more descriptive; the file name is rather general and it could be assumed it contains aliases for more than just one field.

Comment (ayuhito) [reply src/lib/geoip/altnames.ts:2]: How does cityAltnames sound? Or do we want to change the filename itself?

Comment (patrykcieszkowski) [reply src/lib/geoip/altnames.ts:2]: I would name it “cities”, but “cityAltnames” works just fine too.

**Review by patrykcieszkowski — APPROVED** [review]

**Comment by MartinKolarik** [comment]
Waiting for resolving discussion in #163.
